### ISSUE TITLE
Make tablet view responsive 

### ISSUE THREAD

**Issue by kouglas** [openair-collective/Carbon-Forming#66]
## Expected Behavior
content should fit on screen without horizontal scrolling

## Actual Behavior
some content is unable to be seen until the user horizontally scrolls

"competition" page requires a horizontal scroll to see some content. "create competition" page requires a horizontal scroll to see some content. "teams" page has the option of a horizontal scroll. the page that displays a team's details requires a horizontal scroll to see some content. the "edit team" page requires a horizontal scroll to see all content. when there is a competition to view on the 'competition' page the card requires a horizontal scroll in mobile and tablet view

## Steps to Reproduce the Problem
create a team or competition.

**Comment by couchoud** [comment]
The UI/UX has been redesigned, so I'm going to close this for now.
