### ISSUE TITLE
Can't see "logout" hyperlink in tablet view / mobile view

### ISSUE THREAD

**Issue by kouglas** [openair-collective/Carbon-Forming#68]
## Expected Behavior
should be able to see a "logout" hyperlink in the top right-hand corner

## Actual Behavior
in screen sizes with widths <= 1023px the logout hyperlink can't be seen / accessed

## Steps to Reproduce the Problem
change screen size width to <= 1023px

**Comment by couchoud** [comment]
The UI/UX has been redesigned, so I'm going to close this for now.
